### ISSUE TITLE
problem with ocpu_start_app

### ISSUE THREAD

**Issue by mmencuccini** [barupal/chemrich#1]
Hi there
I am trying to use the following command in RStudio:
ocpu_start_app('barupal/chemrich')
 to employ your facility via local host
The command opens up properly and accept further manual input of data file in the Chemrich windows. After several seconds, the following error message appears:
Error: Failed to connect to localhost port 5984: Connection refused
In call:
function (type, msg, asError = TRUE) 
{
    if (!is.character(type)) {
        i = match(type, CURLcodeValues)
        typeName = if (is.na(i)) 
            character()
        else names(CURLcodeValues)[i]
    }
    typeName = gsub("^CURLE_", "", typeName)
    fun = (if (asError) 
        stop
    else warning)
    fun(structure(list(message = msg, call = sys.call()), class = c(typeName, 
        "GenericCurlError", "error", "condition")))
}(7L, "Failed to connect to localhost port 5984: Connection refused", 
    TRUE)
I wonder if you would be so kind as to help me troubleshoot it.

> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] pacman_0.4.6    ChemRICH_0.1.0  opencpu_2.0.5   RCurl_1.95-4.10 bitops_1.0-6    devtools_1.13.4

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15         rstudioapi_0.7       magrittr_1.5         itertools_0.1-3      webutils_0.6         rappdirs_0.3.1       fingerprint_3.5.7   
 [8] lattice_0.20-35      stringr_1.2.0        rcdklibs_2.0         tools_3.4.3          sys_1.5              XLConnect_0.2-14     parallel_3.4.3      
[15] grid_3.4.3           png_0.1-7            git2r_0.21.0         withr_2.1.1          htmltools_0.3.6      iterators_1.0.9      XLConnectJars_0.2-14
[22] openssl_1.0          yaml_2.1.16          digest_0.6.15        RJSONIO_1.3-0        rJava_0.9-9          htmlwidgets_1.0      curl_3.1            
[29] memoise_1.1.0        evaluate_0.10.1      mime_0.5             stringi_1.1.6        compiler_3.4.3       rcdk_3.4.5           jsonlite_1.5        
[36] httpuv_1.3.5    

many thanks

**Comment by barupal** [comment]
Hi, 
I changed the localhost urls to chemrich.fiehnlab.ucdavis.edu. It should fix the error.

**Comment by mmencuccini** [comment]
Hi, thanks for the help. I probably did not understand how to implement your suggestion.

The browser opens up at: http://localhost:5656/ocpu/apps/barupal/chemrich/www/
and the error message that comes up now is: "Error: invalid template name, it must have extension .pptx
In call:
pptx(template = system.file("data", "chem_rich_temp.pptx", package = "reportTemplates")"
However, in R i am still launching:
> ocpu_start_app('barupal/chemrich')
with the following output in RStudio until the error message appears on the browser.
Application 'barupal/chemrich' is up to date (f04739c).
[2018-02-21 12:58:36] OpenCPU single-user server, version 2.0.5
[2018-02-21 12:58:36] Starting 2 new worker(s). Preloading: opencpu, ChemRICH, lattice
[2018-02-21 12:58:37] READY to serve at: http://localhost:5656/ocpu
[2018-02-21 12:58:37] Press ESC or CTRL+C to quit!
[2018-02-21 12:58:37] Opening http://localhost:5656/ocpu/apps/barupal/chemrich
[2018-02-21 12:58:53] POST /ocpu/apps/barupal/chemrich/R/getChemRich_windows
[2018-02-21 12:59:13] Stopped 1 worker(s)
[2018-02-21 12:59:13] GET /ocpu/apps/barupal/chemrich/images/loader.gif
[2018-02-21 12:59:13] Starting 1 new worker(s). Preloading: opencpu, ChemRICH, lattice

Should I launch instead:
ocpu_start_app('fiehnlab.ucdavis.edu/barupal/chemrich') 
or similar. Other ones I have tried don't seem to work.

many thanks
Maurizio

**Comment by barupal** [comment]
You need to re-install the chemrich package. Re-run the following commands again.
```
if (!require("devtools"))
install.packages('devtools', repos="http://cran.rstudio.com/")
if (!require("opencpu"))
install.packages('opencpu', repos="http://cran.rstudio.com/")
if (!require("RCurl"))
install.packages('RCurl', repos="http://cran.rstudio.com/")
library(devtools)
library(RCurl)
source('https://bioconductor.org/biocLite.R')
install_github('barupal/chemrich')
library(chemrich)
library(opencpu)
opencpu$browse('/library/ChemRICH/www')
```
Let me know if you see any errors

**Comment by mmencuccini** [comment]
Hi, thanks again. I have re-installed following the commands above.
In the install_github, I had to add force=T to force re-installation. It installs properly. I then need to invoke
library(ChemRICH)
as opposed to
library(chemrich)
otherwise it does not find it ('there is no package called 'chemrich').
To the opencpu$browse command, it gives an error message:
Error: object 'opencpu' not found (despite having just called library(opencpu), i.e.:
Loading config from C:/Users/Maurizio Mencuccini/Documents/R/win-library/3.4.3/opencpu/config/defaults.conf
Loading config from C:\Users\Maurizio Mencuccini\AppData\Local\opencpu\opencpu/user.conf
Welcome to OpenCPU!)
which forced me to try the other approach of using:
ocpu_start_app
which works fine up to the error message.
I had an issue with Java prior to this (I had not noticed I was running Java 32bit and had to install the 64bit version) and eventually switched to Firefox, which seems able to handle it.

**Comment by barupal** [comment]
This should work, just tested it on my PC. 
```
library(devtools)
library(RCurl)
library(pacman)
pacman::p_load(grid,rcdk, RJSONIO,RCurl, dynamicTreeCut,ape,ggplot2,ggrepel,ReporteRs,XLConnect,phytools,plotrix,plotly, htmlwidgets,DT,extrafont,XLConnect)
install_github('barupal/chemrich')
library(ChemRICH)
library(opencpu)
opencpu::ocpu_start_server()
```
Then go to :
[ChemRICH Local Version](http://localhost:5656/ocpu/library/ChemRICH/www/)

**Comment by barupal** [comment]
I hope you don't see any errors while using ChemRICH locally. Can I close this issue ?

**Comment by johnsonrk2** [comment]
Hi Dinesh, I am getting the same error as mmencuccini when trying to run local ChemRICH on firefox or chrome:

```
Error: invalid template name, it must have extension .pptx
In call:
pptx(template = system.file("data", "chem_rich_temp.pptx", package = "reportTemplates")
```

Perhaps it's an earlier error from loading 'phytools', which I can't figure out how to debug. Another forum (https://www.mail-archive.com/r-sig-phylo@r-project.org/msg04929.html) suggested re-installing 'ape' and then 'phytools' but that has yet to work for me.

I ran these chunks:
```
if (!require("devtools"))
  install.packages('devtools', repos="http://cran.rstudio.com/")
if (!require("opencpu"))
  install.packages('opencpu', repos="http://cran.rstudio.com/")
if (!require("RCurl"))
  install.packages('RCurl', repos="http://cran.rstudio.com/")
if (!require("pacman"))
  install.packages('pacman', repos="http://cran.rstudio.com/")

library(devtools)
library(RCurl)
library(pacman)

source('https://bioconductor.org/biocLite.R')
pacman::p_load(grid,rcdk, RJSONIO,RCurl, dynamicTreeCut,ape,ggplot2,ggrepel,ReporteRs,XLConnect,phytools,plotrix,plotly, htmlwidgets,DT,extrafont,XLConnect)

install_github('barupal/chemrich', force=T)

library(ChemRICH)
library(opencpu)

opencpu::ocpu_start_server()
```

This is the only error or warning section from the console:
```

package 'phytools' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\johnrand\AppData\Local\Temp\RtmpeWV2j3\downloaded_packages

phytools installed
Warning message:
In pacman::p_load(grid, rcdk, RJSONIO, RCurl, dynamicTreeCut, ape,  :
  Failed to install/load:
phytools
```

**Comment by barupal** [comment]
@johnsonrk2  The location of pptx template file is fixed. Can you try it again ?

**Comment by johnsonrk2** [comment]
@barupal Ran with same code above, and still getting this error:

```
Error: invalid template name, it must have extension .pptx



In call:

pptx(template = system.file("data", "chem_rich_temp.pptx", package = "reportTemplates"))
```

**Comment by barupal** [comment]
pptx template was not loading properly. It has to do with an old java version. Can you update your java 
http://www.oracle.com/technetwork/java/javase/downloads/index.html JDK and JRE both. Then run these commands. 
```
install.packages(c("ReporteRs", "ReporteRsjars"))  
pacman::p_load(grid,rcdk, RJSONIO,RCurl, dynamicTreeCut,ape,ggplot2,ggrepel,ReporteRs,XLConnect,phytools,plotrix,plotly, htmlwidgets,DT,extrafont,XLConnect)
install_github('barupal/chemrich', force=T)
library(ChemRICH)
library(opencpu)
opencpu::ocpu_start_server()
```

**Comment by johnsonrk2** [comment]
@barupal Updated JDK and JRE and ran new commands after restarting R with updated packages. Got new error:

```
Error: replacement has 2 rows, data has 0



In call:

`$<-.data.frame`(`*tmp*`, order, value = c(1L, 0L))
```

**Comment by barupal** [comment]
Can you try it with the [example data ](http://chemrich.fiehnlab.ucdavis.edu/example_tempelate.xlsx) ? just to rule out that code is working or not on your computer.

**Comment by johnsonrk2** [comment]
I fixed the phytools failure to load error (had to reinstall ape, phytools and mvtnorm), but still get this from the local run of the example template:

```
Error: C:/Users/johnrand/AppData/Local/Temp/Rtmpg5f1jI/ocpu-temp/x03d1822810/workspace/data/chem_rich_temp.pptx can not be found.



In call:

pptx(template = "./data/chem_rich_temp.pptx")
```

**Comment by johnsonrk2** [comment]
Seems like we have also broken the online version. Data that ran last week now gets this error: 

```
Error: zipping up workbook failed. Please make sure Rtools is installed or a zip application is available to R.
         Try installr::install.rtools() on Windows. If the "Rtools\bin" directory does not appear in Sys.getenv("PATH") please add it to the system PATH 
         or set this within the R session with Sys.setenv("R_ZIPCMD" = "path/to/zip.exe")
```

**Comment by barupal** [comment]
Can you run this command in the r-console - 
```
myDoc <- pptx(template = system.file("data","chem_rich_temp.pptx", package = "chemrich")) 
```
Do you see any error ? I want to make sure that the chemrich package has the powerpoint template and your R console can access it. 

chemrich.fiehnlab.ucdavis.edu is unstable at the moment and I am checking all the errors. I just restarted the docker container so it should work for now.

**Comment by johnsonrk2** [comment]
I run this: 
```

if (!require("devtools"))
  install.packages('devtools', repos="http://cran.rstudio.com/")
if (!require("opencpu"))
  install.packages('opencpu', repos="http://cran.rstudio.com/")
if (!require("RCurl"))
  install.packages('RCurl', repos="http://cran.rstudio.com/")
if (!require("pacman"))
  install.packages('pacman', repos="http://cran.rstudio.com/")
if (!require("ape"))
  install.packages('ape', repos="http://cran.rstudio.com/")

install.packages("mvtnorm")


library(devtools)
library(RCurl)
library(pacman)
library(ape)
library(phytools)

install.packages(c("ReporteRs", "ReporteRsjars"))  
pacman::p_load(grid,rcdk, RJSONIO,RCurl, dynamicTreeCut,ape,ggplot2,ggrepel,ReporteRs,XLConnect,phytools,plotrix,plotly, htmlwidgets,DT,extrafont,XLConnect)
install_github('barupal/chemrich', force=T)
library(ChemRICH)

myDoc <- pptx(template = system.file("data","chem_rich_temp.pptx", package = "chemrich")) 

```
And get this error in the console:
```
> myDoc <- pptx(template = system.file("data","chem_rich_temp.pptx", package = "chemrich"))
Error in pptx(template = system.file("data", "chem_rich_temp.pptx", package = "chemrich")) : 
  invalid template name, it must have extension .pptx
```

**Comment by barupal** [comment]
sorry, try this one - 
```
wbp <- pptx(template = system.file("data","chem_rich_temp.pptx", package = "ChemRICH")) 
```

**Comment by johnsonrk2** [comment]
Got one error for jaxb that caused other warnings later. 

```
0    [main] INFO  org.docx4j.jaxb.Context  - java.vendor=Oracle Corporation
85   [main] INFO  org.docx4j.jaxb.Context  - java.version=1.8.0_161
1653 [main] INFO  org.docx4j.jaxb.NamespacePrefixMapperUtils  - Using NamespacePrefixMapperSunInternal, which is suitable for Java 6
1653 [main] DEBUG org.docx4j.utils.ResourceUtils  - Not using MOXy, since no resource: org/docx4j/wml/jaxb.properties
1653 [main] DEBUG org.docx4j.jaxb.Context  - org/docx4j/wml/jaxb.properties not found via classloader.
1653 [main] DEBUG org.docx4j.utils.ResourceUtils  - Not using MOXy, since no resource: org/docx4j/wml/jaxb.properties
1653 [main] DEBUG org.docx4j.jaxb.Context  - org/docx4j/wml/jaxb.properties not found via classloader.
1653 [main] INFO  org.docx4j.jaxb.Context  - Using Java 6/7 JAXB implementation
4117 [main] INFO  org.docx4j.jaxb.Context  - Not using MOXy.
4313 [main] ERROR org.docx4j.jaxb.Context  - Cannot initialize context
javax.xml.bind.JAXBException: Provider com.sun.xml.internal.bind.v2.ContextFactory could not be instantiated: javax.xml.bind.JAXBException: "org.plutext.jaxb.xmldsig" doesnt contain ObjectFactory.class or jaxb.index
 - with linked exception:
[javax.xml.bind.JAXBException: "org.plutext.jaxb.xmldsig" doesnt contain ObjectFactory.class or jaxb.index]
	at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
	at javax.xml.bind.ContextFinder.find(Unknown Source)
	at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
	at javax.xml.bind.JAXBContext.newInstance(Unknown Source)
	at org.docx4j.jaxb.Context.<clinit>(Context.java:151)
	at org.docx4j.openpackaging.contenttype.ContentTypeManager.parseContentTypesFile(ContentTypeManager.java:671)
	at org.docx4j.openpackaging.io3.Load3.get(Load3.java:132)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:353)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:293)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:243)
	at org.docx4j.openpackaging.packages.OpcPackage.load(OpcPackage.java:226)
	at org.docx4j.openpackaging.packages.PresentationMLPackage.load(PresentationMLPackage.java:104)
	at org.lysis.reporters.docs.pptx4R.setBaseDocument(pptx4R.java:104)
Caused by: javax.xml.bind.JAXBException: "org.plutext.jaxb.xmldsig" doesnt contain ObjectFactory.class or jaxb.index
	at com.sun.xml.internal.bind.v2.ContextFactory.createContext(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at javax.xml.bind.ContextFinder.newInstance(Unknown Source)
	... 13 more
```

**Comment by barupal** [comment]
Did you update your java, JDK and JRE both ?

**Comment by johnsonrk2** [comment]
Yes, and now that I have it properly  working off the JDK 9, there are dependency issues that others have documented that give this error. I haven't found windows solutions for them yet.

```
Error in .jnew(class.pptx4r.document) : 
  java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
```

**Comment by barupal** [comment]
I need to replace the java based pptx export with the officer package. It might take couple of days to do that.

**Comment by barupal** [comment]
I have removed the java dependency, can you check if it works for you?

**Comment by johnsonrk2** [comment]
New error while running locally, but the same data runs fine on the online version:

```
Error: could not find function "ph_with_vg"



In call:

ph_with_vg(., code = print(p2), type = "body", width = 10, height = 8, 

    offx = 0, offy = 0)

```

**Comment by barupal** [comment]
oh, the officer package depends on rvg  and magrittr packages. I added them in the code. Can you re-install and run ChemRICH again. 
```
pacman::p_load(grid,rcdk, RJSONIO,RCurl,rvg,magrittr,dynamicTreeCut,ape,ggplot2,ggrepel,ReporteRs,officer,phytools,plotrix,plotly, htmlwidgets,DT,extrafont,XLConnect)


```

**Comment by johnsonrk2** [comment]
Also had to add "openxlsx" package--and then works great!
